kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

topics:
  user-register: users.register.v1

api:
  base-url: ${API_BASE_URL:http://localhost:8080/api}

log:
  path: ${LOG_PATH:/data/users-processed.log}
